### ISSUE TITLE
Aridity

### ISSUE THREAD

**Issue by zenrabbit** [jennabraun/rdm.gradient#4]
discussed in questions for you too however, MANY ways to calculate aridity - typically you want the biggest possible separation between sites.

I like long-term means, rolling back from but including the sampling year(s)
20-30 years

<img width="946" alt="Screen Shot 2020-06-02 at 5 57 45 PM" src="https://user-images.githubusercontent.com/4825462/83584013-c0b3a780-a4fa-11ea-9bf4-9d1888240c62.png">

http://search.r-project.org/library/ClimClass/html/arid.html

**Comment by cjlortie** [comment]
I have also used long-term MAP but I think aridity index is much better - I prefer deMartonne but there are two others.

**Comment by cjlortie** [comment]
https://climatedataguide.ucar.edu/climate-data/cru-ts-gridded-precipitation-and-other-meteorological-variables-1901

**Comment by cjlortie** [comment]
https://en.wikipedia.org/wiki/Aridity_index
